version: "3.7"
services:
  img-service:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.image-service
    image: image-service
    container_name: image-service
    ports:
      - 3000:3000
    command: bash -c "/usr/wait-for-it.sh minio:9000 && npm start"
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - img_service_network

  minio:
    image: minio/minio:RELEASE.2020-10-18T21-54-12Z
    container_name: minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin1234
    volumes:
      - ./data/minio:/data
    command: "server /data"
    restart: unless-stopped
    networks:
      - img_service_network

networks:
  img_service_network:
    driver: bridge
